<?php
declare(strict_types=1);
/**
 * OrderComment
 *
 * @package     Echron_OrderComment
 * @var $block \Echron\OrderComment\Block\Order\Comment
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($comment = $block->getOrderComment()) : ?>
    <section class="admin__page-section um-ordercomment">
        <div class="admin__page-section-title">
            <span class="title"><?= $escaper->escapeHtml(__('Order Comment')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <?= nl2br($escaper->escapeHtml($comment)) ?>
        </div>
    </section>
<?php endif; ?>
