<?php
declare(strict_types=1);
/**
 * @var \Echron\OrderComment\Block\Order\Comment $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($block->isShowCommentInAccount()) : ?>
    <?php if ($comment = $block->getOrderComment()) : ?>
    <div class="block block-order-comment um-ordercomment-block">
        <div class="block-content">
            <div class="block-title">
                <strong><?php /* @escapeNotVerified */ echo __('Order Comment') ?></strong>
            </div>
            <div class="box-content">
                <?php echo $block->getOrderCommentHtml();?>
            </div>
        </div>
    </div>
    <?php endif; ?>
<?php endif; ?>
