<?php
declare(strict_types=1);
/**
 * @var \Echron\OrderComment\Block\Order\Comment $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($block->isShowCommentInAccount()) : ?>
    <?php if ($comment = $block->getOrderComment()) : ?>
        <div class="block block-order-comment um-ordercomment-block">
            <div class="block-content">
                <div class="block-title">
                    <strong><?= $escaper->escapeHtml(__($block->getFieldLabel())) ?></strong>
                </div>
                <div class="box-content">
                    <?= $block->getOrderCommentHtml() ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
